### PR TITLE
Auto retry fetch errors

### LINKED ISSUE #428: Manager occasionally dying
We're running into a problem where ~10 times a month, a shoryuken manager will die. The logs around the shutdown look like this:

```
Manager failed: No Content-Type received. Service returned the HTTP status code: 500

ERROR: /var/app/current/vendor/bundle/gems/aws-sdk-core-2.7.7/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
/var/app/current/vendor/bundle/gems/aws-sdk-core-2.7.7/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
/var/app/current/vendor/bundle/gems/aws-sdk-core-2.7.7/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
/var/app/current/vendor/bundle/gems/aws-sdk-core-2.7.7/lib/seahorse/client/plugins/response_target.rb:21:in `call'
/var/app/current/vendor/bundle/gems/aws-sdk-core-2.7.7/lib/seahorse/client/request.rb:70:in `send_request'
/var/app/current/vendor/bundle/gems/aws-sdk-core-2.7.7/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
/var/app/current/vendor/bundle/gems/shoryuken-3.1.7/lib/shoryuken/queue.rb:43:in `receive_messages'
/var/app/current/vendor/bundle/gems/shoryuken-3.1.7/lib/shoryuken/fetcher.rb:35:in `receive_messages'
/var/app/current/vendor/bundle/gems/shoryuken-3.1.7/lib/shoryuken/fetcher.rb:16:in `fetch'
/var/app/current/vendor/bundle/gems/shoryuken-3.1.7/lib/shoryuken/manager.rb:82:in `dispatch_single_messages'

Received USR1, will soft shutdown down
```

The error message seems to indicate that SQS returned a 500 when the manager attempted to fetch messages. That exception is caught [here](https://github.com/phstc/shoryuken/blob/b434e1a51798f2f6f71e6349f83753ae687edf35/lib/shoryuken/manager.rb#L46), which results in a shutdown [here](https://github.com/phstc/shoryuken/blob/b434e1a51798f2f6f71e6349f83753ae687edf35/lib/shoryuken/manager.rb#L106).

Does that seem right? Is that the right behavior, or am I missing something?

### PR DESCRIPTION
**Pull request by phstc**
Fixes #428

### CODE REVIEW

File: lib/shoryuken/fetcher.rb [hunk 1]
```diff
@@ -9,20 +9,40 @@ def initialize(group)
...
+        raise if attempts >= max_attempts
+
+        attempts += 1
+
+        logger.debug { "Retrying fetch attempt #{attempts} for #{ex.message}" }
+
+        sleep(attempts)
+
+        retry
+      end
```
Comment (phstc) [inline lib/shoryuken/fetcher.rb]: @ethangunderson WDYT?

File: lib/shoryuken/fetcher.rb [hunk 2]
```diff
@@ -9,20 +9,40 @@ def initialize(group)
     end
 
     def fetch(queue, limit)
-      started_at = Time.now
+      do_with_retry(10) do
```
Comment (ethangunderson) [inline lib/shoryuken/fetcher.rb]: Any thoughts on making this configurable?

File: lib/shoryuken/fetcher.rb [hunk 3]
```diff
@@ -9,20 +9,40 @@ def initialize(group)
...
+      begin
+        yield
+      rescue => ex
+        raise if attempts >= max_attempts
+
+        attempts += 1
+
+        logger.debug { "Retrying fetch attempt #{attempts} for #{ex.message}" }
+
+        sleep(attempts)
```
Comment (ethangunderson) [inline lib/shoryuken/fetcher.rb]: This will act as a backoff until max attempts is reached, right? I like that.

Comment (phstc) [reply lib/shoryuken/fetcher.rb]: @ethangunderson right!

File: lib/shoryuken/fetcher.rb (hunk 2 above)
Comment (phstc) [reply lib/shoryuken/fetcher.rb]: @ethangunderson I usually make that stuff configurable on demand basis, if someone asks to configure, just to avoid adding extra options.

**Comment by waynerobinson** [comment]
Should this rescue from everything… or just fetch-related exceptions?

**Comment by phstc** [comment]
@waynerobinson it used to rescue everything, then nothing, now it's rescuing everything again, but up to 3 attempts. I tried to find fetch-related exceptions before rescuing all, but it's hard to tell what are they. Is this broad rescue causing you issue?

**Comment by waynerobinson** [comment]
Nothing in particular. But in the past I've had issues catching broad exceptions and things like catching TERM signals. 

Would catching all StandardErrors be enough? It's pretty broad, but doesn't include any of the system level exceptions.

**Comment by phstc** [comment]
@waynerobinson makes sense, but I believe `rescue => ex` rescues from `StandardError` and up, for `Interrupt` and others, it would need to be `rescue Exception => ex`.

> StandardError -- default for rescue
> https://ruby-doc.org/core-2.2.0/Exception.html

**Comment by waynerobinson** [comment]
Ahh… fair enough then! 😀

**Comment by phstc** [comment]
@waynerobinson thanks a lot for checking 🍻
