### PR TITLE
Fix miss handling empty batch fetches 

### LINKED ISSUE #375: DeleteMessageBatchRequestEntry errors, extraneous logging
Currently using shoryuken v3.0.7, with the following shoryuken.yml:

```
delay: 25
concurrency: 25
```

starting it via:

```
bundle exec shoryuken --rails --config shoryuken.yml --require ./setup_shoryuken.rb
```

setup_shoryuken.rb looks like:

```
Shoryuken.configure_server do |_config|
  Application.shoryuken_queues.each_value do |q_cfg|
    Shoryuken.add_queue(q_cfg[:q_name], q_cfg[:q_weight])
  end
end

```

worker itself is defined as:

```
class ProcessTurkSqs < ActiveJob::Base
  self.queue_adapter = :shoryuken

  include Shoryuken::Worker

  shoryuken_options queue: QUEUE_NAME,
    auto_delete: true,
    batch: true,
    body_parser: :json

  def perform(_sqs_messages, bodies)
    ...
  end
end

```

In the logs, I see lots of AWS errors on batches with 0 items, as well as extraneous warnings about exponential backoff and auto extend visibility when neither of those options has been set:

```
2017-06-01T22:16:24Z 4900 TID-oxi322j90 ProcessTurkSqs/squatch_mechanical_turk/batch-with-0-messages INFO: started at 2017-06-01 22:16:24 +0000
2017-06-01T22:16:24Z 4900 TID-oxi322j90 ProcessTurkSqs/squatch_mechanical_turk/batch-with-0-messages WARN: Exponential backoff isn't supported for batch workers
2017-06-01T22:16:24Z 4900 TID-oxi322j90 ProcessTurkSqs/squatch_mechanical_turk/batch-with-0-messages WARN: Auto extend visibility isn't supported for batch workers
2017-06-01T22:16:24Z 4900 TID-oxi322j90 ProcessTurkSqs/squatch_mechanical_turk/batch-with-0-messages INFO: failed in: 75.42301599999999 ms
2017-06-01T22:16:24Z 4900 TID-oxi322j90 ERROR: There should be at least one DeleteMessageBatchRequestEntry in the request.
2017-06-01T22:16:24Z 4900 TID-oxi322j90 ERROR: /home/application/.gem/ruby/2.4.0/gems/aws-sdk-core-2.8.14/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
/home/application/.gem/ruby/2.4.0/gems/aws-sdk-core-2.8.14/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
/home/application/.gem/ruby/2.4.0/gems/aws-sdk-core-2.8.14/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
/home/application/.gem/ruby/2.4.0/gems/aws-sdk-core-2.8.14/lib/seahorse/client/plugins/response_target.rb:21:in `call'
/home/application/.gem/ruby/2.4.0/gems/aws-sdk-core-2.8.14/lib/seahorse/client/request.rb:70:in `send_request'
/home/application/.gem/ruby/2.4.0/gems/aws-sdk-core-2.8.14/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
/home/application/.gem/ruby/2.4.0/gems/shoryuken-3.0.7/lib/shoryuken/queue.rb:22:in `delete_messages'
/home/application/.gem/ruby/2.4.0/gems/shoryuken-3.0.7/lib/shoryuken/middleware/server/auto_delete.rb:15:in `call'
/home/application/.gem/ruby/2.4.0/gems/shoryuken-3.0.7/lib/shoryuken/middleware/chain.rb:96:in `block in invoke'
/home/application/.gem/ruby/2.4.0/gems/shoryuken-3.0.7/lib/shoryuken/middleware/server/exponential_backoff_retry.rb:10:in `call'
/home/application/.gem/ruby/2.4.0/gems/shoryuken-3.0.7/lib/shoryuken/middleware/chain.rb:96:in `block in invoke'
/home/application/.gem/ruby/2.4.0/gems/shoryuken-3.0.7/lib/shoryuken/middleware/server/timing.rb:14:in `block in call'
/home/application/.gem/ruby/2.4.0/gems/shoryuken-3.0.7/lib/shoryuken/logging.rb:21:in `with_context'
/home/application/.gem/ruby/2.4.0/gems/shoryuken-3.0.7/lib/shoryuken/middleware/server/timing.rb:8:in `call'
/home/application/.gem/ruby/2.4.0/gems/shoryuken-3.0.7/lib/shoryuken/middleware/chain.rb:96:in `block in invoke'
/home/application/.gem/ruby/2.4.0/gems/shoryuken-3.0.7/lib/shoryuken/middleware/chain.rb:99:in `invoke'
/home/application/.gem/ruby/2.4.0/gems/shoryuken-3.0.7/lib/shoryuken/processor.rb:13:in `process'
/home/application/.gem/ruby/2.4.0/gems/shoryuken-3.0.7/lib/shoryuken/manager.rb:97:in `block in assign'
/home/application/.gem/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/application/.gem/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/application/.gem/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/application/.gem/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/application/.gem/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/application/.gem/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

### PR DESCRIPTION
**Pull request by phstc**
Fix #375

### CODE REVIEW

File: lib/shoryuken/manager.rb [hunk 1]
```diff
@@ -98,7 +98,8 @@ def assign(queue, sqs_msg)
     end
 
     def dispatch_batch(queue)
-      batch = @fetcher.fetch(queue, BATCH_LIMIT)
+      return if (batch = @fetcher.fetch(queue, BATCH_LIMIT)).none?
```
Comment (phstc) [inline lib/shoryuken/manager.rb]: @dotpyfe ☝️ was the issue, it was trying to assign/process/delete all that stuff for empty batches.
