### PR TITLE
fixes #249 Fix daemonize when don't set logfile in command line option

### LINKED ISSUE #249: Can't read logfile option in config file
I can't work fine, for example:
```
rails@085a8fd8cf4a:~/app$ bundle exec shoryuken -R -C config/shoryuken.yml -d
You really should set a logfile if you're going to daemonize
/home/rails/app/vendor/bundle/ruby/2.3.0/gems/shoryuken-2.0.11/lib/shoryuken/cli.rb:80:in `daemonize'
/home/rails/app/vendor/bundle/ruby/2.3.0/gems/shoryuken-2.0.11/lib/shoryuken/cli.rb:34:in `run'
/home/rails/app/vendor/bundle/ruby/2.3.0/gems/shoryuken-2.0.11/bin/shoryuken:6:in `<top (required)>'
/home/rails/app/vendor/bundle/ruby/2.3.0/bin/shoryuken:23:in `load'
/home/rails/app/vendor/bundle/ruby/2.3.0/bin/shoryuken:23:in `<main>'
```

In `shoryuken.yml`, I wrote logfile option:
```yaml
verbose: false
concurrency: 20
delay: 25
pidfile: ./tmp/pids/shoryuken.pid
logfile: ./log/shoryuken.log
```
but shoryuken didn't read logfile option.

I expect this case occur after https://github.com/phstc/shoryuken/pull/219.
`EnvironmentLoader.load` read config file, and initialize logger. And `daemonize` check `Shoryuken.options[:logfile]`. So, if call `daemonize` before `EnvironmentLoader.load`, `daemonize` fail.

Current shoryuken source code, 
https://github.com/phstc/shoryuken/blob/v2.0.11/lib/shoryuken/cli.rb#L32-L39
call `daemonize` before `EnvironmentLoader.load`, so didn't read logifle option in config file.

At the same time, I understand https://github.com/phstc/shoryuken/pull/219 is required.

In sidekiq, read config file options and initialize logger, before `daemonize`.
https://github.com/mperham/sidekiq/blob/v4.1.2/lib/sidekiq/cli.rb#L39-L43

I thought that call initialize logger before `daemonize` in the same manner as sidekiq, but shoryuken have to load Rails before read config file: https://github.com/phstc/shoryuken/pull/197
therefore I can't fix.

What do you think?

### PR DESCRIPTION
**Pull request by h3poteto**
When I didn't give logfile option in command line, shoryuken can't work fine:

```
rails@085a8fd8cf4a:~/app$ bundle exec shoryuken -R -C config/shoryuken.yml -d
You really should set a logfile if you're going to daemonize
/home/rails/app/vendor/bundle/ruby/2.3.0/gems/shoryuken-2.0.11/lib/shoryuken/cli.rb:80:in `daemonize'
/home/rails/app/vendor/bundle/ruby/2.3.0/gems/shoryuken-2.0.11/lib/shoryuken/cli.rb:34:in `run'
/home/rails/app/vendor/bundle/ruby/2.3.0/gems/shoryuken-2.0.11/bin/shoryuken:6:in `<top (required)>'
/home/rails/app/vendor/bundle/ruby/2.3.0/bin/shoryuken:23:in `load'
/home/rails/app/vendor/bundle/ruby/2.3.0/bin/shoryuken:23:in `<main>'
```

In `config/shoryuken.yml`, I wrote logifle option:

``` yaml
verbose: false
concurrency: 20
delay: 25
pidfile: ./tmp/pids/shoryuken.pid
logfile: ./log/shoryuken.log
```

but shoryuken didn't read logfile option.

Current shoryuken source code,
https://github.com/phstc/shoryuken/blob/v2.0.11/lib/shoryuken/cli.rb#L32-L39
call `daemonize` before `EnvironmentLoader.load`, so didn't read logifle option in config file.
That means, it is necessary to call initialize logger before daemonize.

This change intercept old EnvironmentLoader.load, because I reoder method's call to fix daemonize.

### CODE REVIEW

**Comment by phstc** [comment]
hi @h3poteto 

Thanks again, very much appreciated contribution.

Could you check CI?

> /home/travis/build/phstc/shoryuken/spec/spec_helper.rb:19:in `<top (required)>': private method `load' called for Shoryuken::EnvironmentLoader:Class (NoMethodError)
> https://travis-ci.org/phstc/shoryuken/jobs/170067988

**Comment by h3poteto** [comment]
Yes, I am aware CI failed. 
I'm trying to fix specs, please wait a little longer...

File: spec/shoryuken/cli_spec.rb [hunk 1]
```diff
@@ -22,6 +22,12 @@
       allow(launcher).to receive(:stop)
     end
 
+    # reset shoryuken options because class variable hold value which is used previous test case
```
Comment (h3poteto) [inline spec/shoryuken/cli_spec.rb]: When I run all specs, a spec(https://github.com/phstc/shoryuken/pull/261/files#diff-c4306b956d835c4acc8f27cd5f44f968R41) was failed.
Because class variable hold previous option value which is used previoust test case: https://github.com/phstc/shoryuken/pull/261/files#diff-c4306b956d835c4acc8f27cd5f44f968R35

It can't be helped as long as class variable use for Shoryuken.options.

**Comment by phstc** [comment]
Thanks @h3poteto. Added to master 🍻
